if app.export == 0
    n3= app.PontoInicialEditField.Value;
    n4= app.PontoFinalEditField.Value;
    if n3>0 && n4>0 && n3<n4
        conn = database('Saab Matlab','root','');
        sqlquery = sprintf(['SELECT `reator 1`.id ,`umidade`.umidade, `reator 1`.hour,`reator 1`.ppm ,`reator 2`.ppm,`reator 3`.ppm,`reator 4`.ppm,`reator 5`.ppm,`reator 6`.ppm,`reator 7`.`ppm`,`reator 8`.ppm,`reator 9`.ppm,`reator 10`.ppm,`reator 11`.ppm,`reator 12`.ppm,`reator 12`.hour'...
            ' FROM `reator 1`'...
            ' INNER JOIN `reator 2` ON `reator 1`.id = `reator 2`.id'...
            ' INNER JOIN `reator 3` ON `reator 1`.id = `reator 3`.id'...
            ' INNER JOIN `reator 4` ON `reator 1`.id = `reator 4`.id'...
            ' INNER JOIN `reator 5` ON `reator 1`.id = `reator 5`.id'...
            ' INNER JOIN `reator 6` ON `reator 1`.id = `reator 6`.id'...
            ' INNER JOIN `reator 7` ON `reator 1`.id = `reator 7`.id'...
            ' INNER JOIN `reator 8` ON `reator 1`.id = `reator 8`.id'...
            ' INNER JOIN `reator 9` ON `reator 1`.id = `reator 9`.id'...
            ' INNER JOIN `reator 10` ON `reator 1`.id = `reator 10`.id'...
            ' INNER JOIN `reator 11` ON `reator 1`.id = `reator 11`.id'...
            ' INNER JOIN `reator 12` ON `reator 1`.id = `reator 12`.id'...
            ' INNER JOIN `umidade` ON `reator 1`.id = `umidade`.id'...
            ' WHERE `reator 1`.id >= %d AND `reator 1`.id <= %d;'],n3,n4);
        x = exec(conn,sqlquery);
        %x = select(conn,sqlquery);
        x = fetch(x);
        
        %x = cell2table(x.Data);
        %sprintf('%s',x)
        %data = select(conn,sqlquery)
        %x = cell2mat(x.Data);
        %show = num2cell(true(5,1));
        app.UITable.Data = [x.Data(1:end,1) x.Data(1:end,2) x.Data(1:end,3) x.Data(1:end,4) x.Data(1:end,5) x.Data(1:end,6) x.Data(1:end,7) x.Data(1:end,8) x.Data(1:end,9) x.Data(1:end,10) x.Data(1:end,11) x.Data(1:end,12) x.Data(1:end,13) x.Data(1:end,14) x.Data(1:end,15) x.Data(1:end,16)];
        
    end
end
if app.export==1
    n3= app.PontoInicialEditField.Value;
    n4= app.PontoFinalEditField.Value;
    if n3>0 && n4>0 && n3<n4
        conn = database('Saab Matlab','root','');
        sqlquery = sprintf(['SELECT `reator 1`.id ,`umidade`.umidade, `reator 1`.hour,`reator 1`.ppm ,`reator 2`.ppm,`reator 3`.ppm,`reator 4`.ppm,`reator 5`.ppm,`reator 6`.ppm,`reator 7`.`ppm`,`reator 8`.ppm,`reator 9`.ppm,`reator 10`.ppm,`reator 11`.ppm,`reator 12`.ppm,`reator 12`.hour'...
            ' FROM `reator 1`'...
            ' INNER JOIN `reator 2` ON `reator 1`.id = `reator 2`.id'...
            ' INNER JOIN `reator 3` ON `reator 1`.id = `reator 3`.id'...
            ' INNER JOIN `reator 4` ON `reator 1`.id = `reator 4`.id'...
            ' INNER JOIN `reator 5` ON `reator 1`.id = `reator 5`.id'...
            ' INNER JOIN `reator 6` ON `reator 1`.id = `reator 6`.id'...
            ' INNER JOIN `reator 7` ON `reator 1`.id = `reator 7`.id'...
            ' INNER JOIN `reator 8` ON `reator 1`.id = `reator 8`.id'...
            ' INNER JOIN `reator 9` ON `reator 1`.id = `reator 9`.id'...
            ' INNER JOIN `reator 10` ON `reator 1`.id = `reator 10`.id'...
            ' INNER JOIN `reator 11` ON `reator 1`.id = `reator 11`.id'...
            ' INNER JOIN `reator 12` ON `reator 1`.id = `reator 12`.id'...
            ' INNER JOIN `umidade` ON `reator 1`.id = `umidade`.id'...
            ' WHERE `reator 1`.id >= %d AND `reator 1`.id <= %d;'],n3,n4);
        cmd = select(conn,sqlquery);
        caixatexto = app.ExportField.Value;
        palavra = strcat(caixatexto,'.xls');
        writetable(cmd,palavra,'WriteVariableNames',false)
    end
end